pipeline {
    agent any
    stages {
        stage('Push compose file to server') {
            when {
                branch 'master'
            }
            steps {
                script {
                    sh "sshpass -p '$USERPASS' -v scp -o StrictHostKeyChecking=no database/es/docker-compose.yml $USERNAME@$qa_ip:~/docker-compose.yml"
                }
            }
        }
        stage('DeployToQA') {
            when {
                branch 'master'
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'qa_server_credentials', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
                    script {
                        try {
                            sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$qa_ip \"docker-compose rm -f\""
                            sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$qa_ip \"docker-compose up\""
                        } catch (err) {
                            echo: 'caught error: $err'
                        }
                    }
                }
            }
        }
    }
}