version: '2.2'

services:
  django_db:
    image: postgres
    container_name: postgres_dj_container
    environment:
      - POSTGRES_PASSWORD=${DJ_DB_PASSWORD}
    volumes:
      - postgres_dj_db_data:/var/lib/postgresql/data
    ports:
      - 8884:5432

  web_interface:
    image: frouk/webmail
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - django_db

volumes:
  postgres_dj_db_data:
    driver: local