version: '2.2'

services:
  django_db:
    image: postgres
    container_name: postgres_dj_container
    environment:
      - POSTGRES_PASSWORD=${DJ_DB_PASSWORD}
    volumes:
      - postgres_dj_db_data:/var/lib/postgresql/data
    ports:
      - 8884:5432
    networks:
      - djangonet

  web_interface:
    image: frouk/webmail
    command: python3 odms_webmail/manage.py runserver 0.0.0.0:8000
    environment:
      - DJ_SECRET_KEY=${DJ_SECRET_KEY}
      - DJ_DB_PASSWORD=${DJ_DB_PASSWORD}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
    depends_on:
      - django_db
    ports:
      - 8885:8000
    networks:
      - djangonet
volumes:
  postgres_dj_db_data:
    driver: local

networks:
  djangonet: