pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            when {
                branch 'master'
            }
            steps {
                script {
                    dir('parser'){
                        app = docker.build("frouk/email_parser")
                    }
                }
            }
        }
        stage('Push Docker Image') {
            when {
                branch 'master'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub_login') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }
        stage('DeployToQA') {
            when {
                branch 'master'
            }
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'postgres_db_credentials', usernameVariable: 'POSTGRES_DB_USERNAME', passwordVariable: 'POSTGRES_DB_PASSWORD'),
                    usernamePassword(credentialsId: 'qa_server_credentials', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')
                ]){
                    script {
                        sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$qa_ip \"docker pull frouk/email_parser:${env.BUILD_NUMBER}\""
                        try {
                            sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$qa_ip \"docker stop email_parser\""
                            sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$qa_ip \"docker rm email_parser\""
                        } catch (err) {
                            echo: 'caught error: $err'
                        }
                        sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$qa_ip \"docker run --restart always --network postgresnet -e \"POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD\" -e \"ES_SERVER_ENDPOINT=elasticsearch\" --name email_parser -v /var/mail:/var/mail -td frouk/email_parser:${env.BUILD_NUMBER}\""
                    }
                }
            }
        }
    }
}